image: dockerhub.mc.box/mc/phpenv74:3.4.0
stages:
   - test
   - package-and-deploy

'unittests':
  stage: test
  script:
    - composer install --prefer-dist
    - ./vendor/bin/phpunit --colors=never --configuration phpunit.xml
  except:
    - tags

'phpcs':
  stage: test
  script:
    - sh ./phpcs/phpcs.sh
  except:
    - tags

'upload':
    variables:
      CI_PACKAGE_NAME: "vcom-api-client"
    stage: package-and-deploy
    script:
      - script/cibuild ${CI_PROJECT_DIR} ${CI_COMMIT_REF_NAME} ${CI_PACKAGE_NAME}
    image: "dockerhub.mc.box/mc/pre-deploy:5.1.0"
    only:
      - develop
      - tags
